import type { EntryDoc } from './extract.ts';

const FRONTMATTER = `---
title: Reference
description: The public functions, classes and types of @yarunoka/core, generated from their doc comments.
sidebar:
  order: 2
---

<!-- Generated by \`npm run docs:generate\`. Edit the doc comments in src/, not this file. -->
`;

const SECTIONS: readonly (readonly [string, EntryDoc['kind']])[] = [
  ['Functions', 'function'],
  ['Classes', 'class'],
  ['Constants', 'constant'],
  ['Types', 'type'],
];

/**
 * Renders extracted entries into the single reference page. Sections
 * come in a fixed order and entries alphabetically within one, so the
 * same source always produces byte-identical output, which the
 * freshness check relies on.
 */
export function render(entries: readonly EntryDoc[]): string {
  let page = FRONTMATTER;

  for (const [title, kind] of SECTIONS) {
    const section = entries
      .filter((entry) => entry.kind === kind)
      .toSorted((a, b) => (a.name < b.name ? -1 : 1));

    if (section.length === 0) {
      continue;
    }

    page += `\n## ${title}\n`;

    for (const entry of section) {
      page += entrySection(entry);
    }
  }

  return page;
}

function entrySection(entry: EntryDoc): string {
  let section = `\n### ${entry.name}\n\n`;

  // Types always fence; anything else fences once its declaration
  // spans lines (a one-line spelling inside a fence would read heavier
  // than the inline code every other entry uses).
  section +=
    entry.kind === 'type' || entry.declaration.includes('\n')
      ? `\`\`\`ts\n${entry.declaration}\n\`\`\`\n`
      : `\`${entry.declaration}\`\n`;

  if (entry.doc !== '') {
    section += `\n${entry.doc}\n`;
  }

  if (entry.members !== undefined && entry.members.length > 0) {
    section += '\n#### Members\n\n';

    for (const member of entry.members) {
      const summary = member.doc.split('\n\n')[0] ?? '';

      section += `- \`${member.signature}\`${summary === '' ? '' : ` — ${summary}`}\n`;
    }
  }

  return section;
}
