// What: rendering extracted entries into the single reference page —
// fixed section order, alphabetical entries, inline code for one-line
// declarations, fenced blocks for types and multi-line constants,
// member bullets with the first doc paragraph as the summary.
import assert from 'node:assert/strict';
import { test } from 'node:test';
import type { EntryDoc } from '../extract.ts';
import { render } from '../render.ts';

const entries: EntryDoc[] = [
  {
    name: 'parse',
    kind: 'function',
    declaration: 'parse(input: string): Doc',
    doc: 'Reads a document.',
  },
  {
    name: 'build',
    kind: 'function',
    declaration: 'build(document: Doc): object',
    doc: 'Writes a document.',
  },
  {
    name: 'Doc',
    kind: 'type',
    declaration: 'type Doc = {\n  readonly ok: boolean;\n};',
    doc: 'A document.',
  },
  {
    name: 'VERSION',
    kind: 'constant',
    declaration: "const VERSION = '1.0'",
    doc: 'The version.',
  },
  {
    name: 'WORDS',
    kind: 'constant',
    declaration: "const WORDS: readonly string[] = [\n  'alpha',\n]",
    doc: 'The words.',
  },
  {
    name: 'Failure',
    kind: 'class',
    declaration: 'class Failure extends Error',
    doc: 'A failure.',
    members: [
      { signature: 'readonly code: string', doc: 'What kind.\n\nDetail left out of the bullet.' },
      { signature: 'constructor(code: string)', doc: '' },
    ],
  },
];

const page = render(entries);

test('opens with the frontmatter and the generated-file marker', () => {
  assert.ok(page.startsWith('---\ntitle: Reference\n'));
  assert.ok(page.includes('sidebar:\n  order: 2\n---\n'));
  assert.ok(page.includes('<!-- Generated by `npm run docs:generate`.'));
});

test('sections come in a fixed order and entries alphabetically within one', () => {
  const positions = [
    '## Functions',
    '### build',
    '### parse',
    '## Classes',
    '### Failure',
    '## Constants',
    '### VERSION',
    '## Types',
    '### Doc',
  ].map((heading) => page.indexOf(heading));

  assert.ok(positions.every((position) => position >= 0));
  assert.deepEqual(
    positions,
    positions.toSorted((a, b) => a - b),
  );
});

test('a function renders as inline code followed by its doc', () => {
  assert.ok(page.includes('### parse\n\n`parse(input: string): Doc`\n\nReads a document.\n'));
});

test('a type renders its declaration as a fenced block', () => {
  assert.ok(
    page.includes(
      '### Doc\n\n```ts\ntype Doc = {\n  readonly ok: boolean;\n};\n```\n\nA document.\n',
    ),
  );
});

test('a one-line constant renders as inline code', () => {
  assert.ok(page.includes("### VERSION\n\n`const VERSION = '1.0'`\n\nThe version.\n"));
});

test('a multi-line constant renders its declaration as a fenced block', () => {
  assert.ok(
    page.includes(
      "### WORDS\n\n```ts\nconst WORDS: readonly string[] = [\n  'alpha',\n]\n```\n\nThe words.\n",
    ),
  );
});

test('a class renders member bullets with the first doc paragraph as summary', () => {
  assert.ok(page.includes('### Failure\n\n`class Failure extends Error`\n\nA failure.\n'));
  assert.ok(page.includes('- `readonly code: string` — What kind.\n'));
  assert.ok(page.includes('- `constructor(code: string)`\n'));
});

test('an empty section is left out entirely', () => {
  assert.ok(!render(entries.filter((entry) => entry.kind === 'function')).includes('## Classes'));
});

test('the page ends with a single trailing newline', () => {
  assert.ok(page.endsWith('\n'));
  assert.ok(!page.endsWith('\n\n'));
});
